FROM aibox

# docker build -t aibox-kafka -f Dockerfile.kafka .

## Kafka integrations:
RUN conda install -c conda-forge/label/gcc7 kafka-python 
RUN apt-get install -y build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev cmake && \
    cd /tmp && \
    git clone https://github.com/facebook/rocksdb.git && \
    cd rocksdb  && \
    cmake . && \
    make -j8 && \
    make install && \
    rm -rf /tmp/rocksdb
RUN pip install "faust[rocksdb, fast, statsd]" && rm -rf /root/.cache/pip
