FROM andaag/aibox_cuda9

# docker build -t aibox-githead -f Dockerfile.cuda9_githead .

RUN pip install git+git://github.com/fastai/fastai.git 
RUN conda install joblib
RUN conda install memory_profiler line_profiler
